### ISSUE TITLE
Sponsor options out of stock

### ISSUE THREAD

**Issue by Akylos5885** [Fluufff/Website-issues#20] opened 2020-03-10 17:38 UTC
Similar to https://github.com/Fluufff/Website-issues/issues/16 and https://github.com/Fluufff/Website-issues/issues/19. 

All sponsor options are out of stock.

**Comment by gabrielTach** [comment] 2020-03-10 18:17
Duplicate of #16

**Closed as completed by gabrielTach** 2020-03-10 18:17 UTC
