### ISSUE TITLE
[Bug] Translation buttons don't work

### ISSUE THREAD

**Issue by AVRSkyline** [Fluufff/Website-issues#43] opened 2022-05-12 06:02 UTC
**How to reproduce**
(Inconsistent behaviour)

1. Go to homepage
2. Change language
3. Go to other page
4. Try to change language
5. Go back to homepage
6. Try to change language
7. Repeat previous steps. At some point nothing happens when selecting another language.

**Description**
The language tab opens, but nothing changes when you select a different language.

**Notes **
- Reproduced on Firefox. Not reproducible on Chrome

**Comment by gabrielTach** [comment] 2022-05-12 15:03
I am not able to reproduce it in Firefox 100.0 (Linux).

Can you force the refresh and try again (Crtl+F5) or empty the cache of the Browser?

Can you clarify if this is only happening in Firefox?

**Comment by HybridFox** [comment] 2022-05-12 15:07
Cannot reproduce either, but i will switch out the logic to make it more robust

**Comment by gabrielTach** [comment] 2022-05-15 15:10
Closing this ticket as it seems to be fixed. (potentially a server configuration issue)

**Closed as completed by gabrielTach** 2022-05-15 15:10 UTC
Labels: bug
