### ISSUE TITLE
Standard whole bedrooms out of stock

### ISSUE THREAD

**Issue by Akylos5885** [Fluufff/Website-issues#19] opened 2020-03-10 17:34 UTC
Similar to https://github.com/Fluufff/Website-issues/issues/16. Only single spots are available for Standard rooms. No whole bedrooms can be taken. They can be selected, but not be added to the cart.

**Comment by gabrielTach** [comment] 2020-03-10 18:18
Duplicate of #16

**Closed as completed by gabrielTach** 2020-03-10 18:18 UTC
